CHANGES.rst
README.rst
click_odoo_contrib/initdb.py
setup.py
tests/test_initdb.py

```
Usage: click-odoo-initdb [OPTIONS]
Create an Odoo database with pre-installed modules.
Almost like standard Odoo does, except this manages a cache of database
templates with the exact same addons installed. This is mostly intended to
save time when running tests.
Options:
-c, --config PATH        Specify the Odoo configuration file. Other ways to
provide it are with the ODOO_RC or OPENERP_SERVER
environment variables, or ~/.odoorc (Odoo >= 10) or
~/.openerp_serverrc.
--log-level TEXT         Specify the logging level. Accepted values depend
on the Odoo version, and include debug, info, warn,
error.  [default: warn]
--logfile PATH           Specify the log file.
-n, --new-database TEXT  [required]
-m, --modules TEXT       Comma separated list of addons to install.
[default: base] …
```

[WIP] click-odoo-initdb

---

CHANGES.rst
click_odoo_contrib/initdb.py
tests/test_initdb.py

...ending up with an "already exists" error when creating
the cached template

handle situations where two initdb start at the same time

---

CHANGES.rst
click_odoo_contrib/initdb.py
click_odoo_contrib/manifest.py

These are autoinstalled by Odoo.
@ThomasBinsfeld @Cedric-Pigeon

initdb: include modules with active=True in hash computation

---

.travis.yml
tox.ini

Could be also done with "_" all together, but must be consistent.

[FIX] tox env typo

---

tests/scripts/install_odoo.py

Because Odoo < 11 does not work with the latest pyyaml

[FIX] Odoo not compatible with pyyaml 5.1

---

CHANGES.rst
click_odoo_contrib/initdb.py
click_odoo_contrib/update.py
tests/test_manifest.py
tests/test_update.py

This is WIP until https://github.com/acsone/click-odoo/pull/31 is released. It makes use of that new feature in click-odoo to allow running these scripts in pre-release versions.
@Tecnativa TT19268

[FIX] Use parse_version to compare versions

---

.flake8
README.rst
click_odoo_contrib/update.py
tests/test_update.py

With this patch, if you update a database while another Odoo instance is running (such as i.e. a production instance), the production instance will not be locked just because there's a DB lock.
DB locks can happen i.e. when 2 or more transactions are happening in parallel and one of them wants to modify data in a field while another one is modifying the field itself. For example, imagine that a user is modifying a `res.partner`'s name, while another update process is adding a `UNIQUE` constraint in the `name` field of the `res_partner` table. This would produce a deadlock where each transaction is waiting for the other one to finish, and thus both the production instance and the update instance would be locked infinitely until one of them is aborted.
You cannot detect such problem with …

update: Parallel DB locks watcher

---

README.rst
click_odoo_contrib/update.py
newsfragments/68.feature
tests/test_update.py

This allows to anticipate better the impact of an update. Let me know if this approach is correct and/or if it needs any change.
Awesome project BTW :)
@ForgeFlow

click-odoo-update: add dry-run option to evaluate addons to update before actually updating.

---

README.rst
click_odoo_contrib/backupdb.py
click_odoo_contrib/restoredb.py
newsfragments/32.feature
setup.py
tests/test_restoredb.py

add restoredb command

---

tests/scripts/install_odoo.py

Install Odoo requirements.txt instead of dependencies
from setup.py, for stability. Additionally, fetch requirements.txt
for OCB because older versions are more likely to be maintained.

tests: install requirements.txt from OCA/OCB

---

README.rst
click_odoo_contrib/makepot.py
tests/data/test_makepot/addon_test_makepot/i18n/fr.po.fuzzy
tests/data/test_makepot/addon_test_makepot/i18n/fr.po.old
tests/test_makepot.py

Allow adding `--no-fuzzy-matching` flag to `msgmerge` command through makepot command line flag.
Allow for adding `--purge-old-translations` flag to remove old translation as comments in generated .po files.
@Tecnativa
TT26747
ping @Yajo

Add --no-fuzzy-matching option to makepot

---

click_odoo_contrib/update.py
newsfragments/97.feature

This should not be necessary, but it does no harm.
And it helps in combination with https://github.com/odoo/odoo/pull/72661 until a better solution is found in Odoo core.

click-odoo-update: also consider modules in 'to upgrade' state

---

README.rst
click_odoo_contrib/copydb.py
newsfragments/86.feature
tests/test_copydb.py

This is useful if filestore for one db `copy` that is a copy of `base` mounted on top of the base filestore via a filesystem that facilitates deduplication of assets in the root filesystem (e.g. mounting `copy` onto `base` with https://manpages.debian.org/jessie/aufs-tools/mount.aufs.8.en.html)
And also should improve performance of copydb if filestore already exists and one only needs to copy the changes (new files only).
Info @wt-io-it

enable copying filestore in diff mode

---

click_odoo_contrib/_dbutils.py
click_odoo_contrib/initdb.py
newsfragments/105.bugfix
tests/test_initdb.py

This usage is safe are we are not using the ORM but the underlying pg cursor.
closes #105

Silence Odoo 15 noisy warnings about using autocommit

---

click_odoo_contrib/update.py
newsfragments/119.bugfix

click-odoo-update does not work after odoo 15
in odoo master this is because load_information_description_file() is deprecated
see https://github.com/odoo/odoo/blob/master/odoo/modules/module.py#L413
I propose this pr to fix this, tested for an odoo 13 and an odoo master

[UPD] adapt click-odoo-update for odoo 16

---

click_odoo_contrib/update.py

This PR is going to fix issue since #119 
Assume we are using Odoo 15, now we have
`odoo.tools.parse_version("15")` < `odoo.tools.parse_version(odoo.release.version)` < `odoo.tools.parse_version("16")`
Then that condition will return false and `_is_installable` will also return false since `get_manifest` doesn't exists in Odoo 15
So it is better to change the expression to `odoo.tools.parse_version(odoo.release.version)` < `odoo.tools.parse_version("16")` to include all Odoo 15 version

Fix click-odoo-update for odoo 15

---

click_odoo_contrib/addons_analyse.py

In _addons_info_to_rows an error occurred with Python3 because values() method is not returning a list anymore, but a view object

[FIX] addons_analyse.py: compatibility with python3

---

click_odoo_contrib/update.py
newsfragments/125.feature

A modification in tests alone should not require a database upgrade.

[IMP] click-odoo-update: exclude tests from checksum

---

setup.py

The script does not exist and was deprecated quite some time ago.

Remove the click-odoo-upgrade entry point

---

click_odoo_contrib/update.py

Just a simple refactoring to allow our scripts to check beforehand if anything is going to be updated.

[REF] click-odoo-update: refactor _get_modules_to_update as a separate method

---

README.rst
click_odoo_contrib/_dbutils.py
click_odoo_contrib/dropdb.py
click_odoo_contrib/listdb.py
setup.py
tests/test_listdb.py
tests/test_restoredb.py

Getting DBs for Odoo is tricky:
1. Postgres must be running.
2. Odoo must be available.
3. Database must exist.
4. Some basic tables such as `ir_module_module` must exist.
Some scripts in this repo operate on just one database. But what if you don't know the DB name in advance? You need a way to get them.
With this new script, you can do now:
```shell
click-odoo-listdb | grep --invert-match cache | xargs click-odoo-update -d
```
@moduon MT-1075

feat(click-odoo-listdb): handy script for listing odooable databases

---

click_odoo_contrib/update.py
newsfragments/144.feature

Hello,
I ran in really strange bug in Odoo 14 when playing click-odoo-update on database with no module to upgrade.
I guess there is no need to do it when no modules have changed, what do you think @sbidoul ?
Here the bug I ran in and how to reproduce it. I did only test with version 14.
1) Create a new database with sale module.
2) Check the res.users group view (`base.user_groups_view`), you should have something like that to display the sales 3 group level  : 
```
<group col="2" string="Sales">
<newline/>
<field name="sel_groups_20_21_22" attrs="{'readonly': [('sel_groups_1_9_10', '!=', 1)]}"/>
<newline/>
```
3) Run click-odoo-update twice, on first call, it will update all and create the hash for the modules, on second call, it won't update any module.
Then, check the …

[FIX] click-odoo-update : avoid update mode when there are no module to update.

---

click_odoo_contrib/backupdb.py

As talked about in #129 
the backup no longer works in v18
This implementation should be backwards compatible till v11

[FIX] use subprocess to take backup

---

click_odoo_contrib/restoredb.py

Use subprocess to restore the db
as the exec_pg_commands are no longer available

[FIX] use subprocess to restore the database

---

README.rst
click_odoo_contrib/update.py
tests/test_update.py

If click-odoo-contrib is not installed from the beginning,
you can now initialise the hashes and then start using click-odoo-update.

click-odoo-update: add--only-compute-hashes
